### ISSUE TITLE
Feature Request: Ability to select different subject Kind(s)

### ISSUE THREAD

**Issue by svilenkov** [sighupio/permission-manager#117]
It would be great to have the ability to specify different subject Kind(s) 
for example:

```yaml
subjects:
# Google Cloud user account
- kind: User
  name: janedoe@example.com
# Kubernetes service account
- kind: ServiceAccount
  name: johndoe
# IAM service account
- kind: User
  name: test-account@test-project.iam.gserviceaccount.com
# Google Group
- kind: Group
  name: accounting-group@example.com
  ```
  
 This would allow easy mapping between Google Cloud user acocunts and ClusterRoleBinding
  
 Likely related to: #42
