### ISSUE TITLE
Feature: allow flexible subjects for clusterrolebindings/rolebindings

### ISSUE THREAD

**Issue by stjudecloud-cloudy** [sighupio/permission-manager#41]
In Azure AKS users can have access granted by either by their AD group membership, or directly using AD user ID. It would be extremely useful, if  user access management could be done using permission-manager. 

In order to achieve it, it would be necessary to allow different kind of subjects for both clusterrolebinding and rolebinding.
This is an example of clusterrolebinding used for assigning RBAC to AD group:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-developer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: id-redacted
```
Similarly `kind: User` can be used to grant a specific user access to Kubernetes using RBAC.
Ideally, web interface should allow creation of different kind of subjects and used created subjects for access grants.
