### ISSUE TITLE
How to change password ?

### ISSUE THREAD

**Issue by protonwebmaster** [sighupio/permission-manager#7]
Hello, I am learning Kubernetes.

After deployment to 

> http://localhost:4000

 I have a problem to login.

First I tried to login with user : **admin** and password : **password**, but this do not working.

Here is my configuration : 
```
- name: BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-password-secret
                  key: password
```
And how can I change this password ?

Thanks for any help.
