### ISSUE TITLE
Errors with k8s 1.22

### ISSUE THREAD

**Issue by vitjok27** [sighupio/permission-manager#71]
Hello

Looks like permission-mamanher is not supporing newer Kubernetes versions. Tried to install it on 1.22 and was getting following errors:
kubectl apply -f https://github.com/sighupio/permission-manager/releases/download/v1.7.0-rc3/crd.yml
**error:** unable to recognize "https://github.com/sighupio/permission-manager/releases/download/v1.7.0-rc3/crd.yml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

kubectl apply -f https://github.com/sighupio/permission-manager/releases/download/v1.7.0-rc3/deploy.yml
service/permission-manager created
deployment.apps/permission-manager created
serviceaccount/permission-manager created
clusterrole.rbac.authorization.k8s.io/permission-manager created
**error:** unable to recognize "https://github.com/sighupio/permission-manager/releases/download/v1.7.0-rc3/deploy.yml": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"

Is this something we could have any time soon?
Thanks!

**Comment by nikever** [comment]
Hi vitjok27,
thanks for using permission-manager. Support for Kubernetes 1.22 it's on the roadmap but I can't give you an ETA yet.

For now, you can use the following `crd.yml` that is compatible with Kubernetes v1.22:

```yaml
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "permissionmanagerusers.permissionmanager.user"
spec:
  group: "permissionmanager.user"
  versions: 
    - name: "v1alpha1"
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  minLength: 2
  scope: "Cluster"
  names:
    plural: "permissionmanagerusers"
    singular: "permissionmanageruser"
    kind: "Permissionmanageruser"    
```

Then apply `seed.yml` and `deploy.yml` as before:

```bash
kubectl apply -f https://github.com/sighupio/permission-manager/releases/download/v1.7.0-rc3/seed.yml
kubectl apply -f https://github.com/sighupio/permission-manager/releases/download/v1.7.0-rc3/deploy.yml

We have tested it in a local environment and everything seems to be working, let me know if you find any issues.

Nico
