### ISSUE TITLE
Broken access view in UI for custom template

### ISSUE THREAD

**Issue by andrey-gava** [sighupio/permission-manager#84]
I was in need to create access rights for user to read resources in only one specific namespace. 
So I created ClusterRole:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: template-namespaced-resources___readonly
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - pods
  - pods/log
  - pods/portforward
  - podtemplates
  - replicationcontrollers
  - resourcequotas
  - secrets
  - services
  - events
  - daemonsets
  - deployments
  - replicasets
  - ingresses
  - networkpolicies
  - poddisruptionbudgets
  - statefulsets
  - tlsstores
  - middlewares
  verbs:
  - get
  - list
  - watch
```
Despite granted access rights works, and user can read needed resources, the grunted rights not shown in UI poperly.
![изображение](https://user-images.githubusercontent.com/59727632/133384700-bddea807-a663-438f-a8ef-63d44dddc309.png)

![изображение](https://user-images.githubusercontent.com/59727632/133384784-9fa5b3a7-3878-46ea-b012-58739808d3fb.png)

Its same for v1.6 and 1.7.1-rc1
