### ISSUE TITLE
certificate-authority-data has no data in kubeconfig

### ISSUE THREAD

**Issue by hillbun** [sighupio/permission-manager#92]
```
---
apiVersion: v1
kind: Config
current-context: kkk@cluster.local
clusters:
  - cluster:
      certificate-authority-data: 
      server: https://127.0.0.1:6443
    name: cluster.local
contexts:
  - context:
      cluster: cluster.local
      user: kkk
      namespace: permission-manager
    name: kkk@cluster.local
users:
  - name: kkk
    user:
      token: eyJhbGciOiJSUzI1NiIsImtpZCI6InJCSEw5bnVQcDc3YVY1RVozSkVlV0lGeG5aTTFzcG4xUFVETlQtekFuYXcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJwZXJtaXNzaW9uLW1hbmFnZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoia2trLXRva2VuLWJ4MnR3Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImtrayIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6Ijc1Mzk2NzRiLWZhMzItNDY1Mi05M2FiLWNlNTJhYzg3ZGE5YiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpwZXJtaXNzaW9uLW1hbmFnZXI6a2trIn0.ZWHhyuAIYOpBpAAS_128JV2YM_ELL3As9gkrx07yaBrOhm5G5qdl4cGl1Us3CX6M90MyOE678RyK2qUiSuG7KIMJXGAAz71Qd5mwF3Mbth4Kj7GPHVCtAP5jmeCX1hUJPiA2ZNUMyXfXG6lfL052y40uDPM6A4Nk9jJmnX2pM2TUUPXLixCfn5zziYndhn29CHaWjduZ3SsPEnB446u5ODx1kadtcJNNxjx_pkS2XhcqNH-KOArv6WY370f2mPgNAdQZgXE0TZWMUTi5tWKzmaGMA-Ka--TCD0bL6L5nxHxJkkRhXoU7bBdYiew3CXBx7x3CWxc9Nu582WgwmFbfiw
```
